### ISSUE TITLE
라이선스 문의

### ISSUE THREAD

**Issue by ryush00** [McbeRank/McbeRank#1]
McbeRank는 어떤 라이선스를 사용하고 있는지 불명확한 것 같습니다.

혹시 가능하시다면 알려주시면 감사하겠습니다.

**Comment by solo5star** [comment]
안녕하세요, McbeRank에 관심을 가져주셔서 감사합니다.
말씀하신대로 라이선스가 불명확한 것 같아, MIT 라이선스를 적용하였습니다.
그 외 본 그룹 내에서 라이선스가 명시되지 않은 부분(제가 fork한 레포에서 추가한 코드 또는 제가 작성한 부분) 또한 동일하게 MIT로 간주해주세요.

감사합니다.

**Comment by ryush00** [comment]
답변 감사합니다! 😄
